version: 1.0.{build}
clone_depth: 3
skip_tags: true

install:
  - set PATH=C:\Ruby22\bin;%PATH%
  - bundle install
  - ps: C:\Projects\marktest\puppet-configure.ps1

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

before_test:
  - ruby -v
  - gem -v
  - bundle -v
  - puppet --help  

configuration:

- Master 

platform:

- x64

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

image:

- Visual Studio 2017

environment:

  matrix:

  - BUILD_MODE: MSBuild

# Disable build through solution file
build: off

