version: 1.0.{build}
clone_depth: 3
skip_tags: true

install:
  - bundle install
  - ps: C:\Projects\marktest\puppet-configure.ps1
  - ps: Restart-Computer -Force
  - PS: Start-Sleep -s 200

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

before_test:
  - ruby -v
  - gem -v
  - bundle -v
  - PS: C:\Projects\marktest\docker_test.ps1

configuration:

- Master 

platform:

- x64

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

image:

- Visual Studio 2017

environment:

  matrix:

  - BUILD_MODE: MSBuild

# Disable build through solution file
build: off

