version: 1.0.{build}
clone_depth: 3
skip_tags: true

install:
  - set PATH=C:\Ruby22\bin;%PATH%
  - bundle install

before_test:
  - ruby -v
  - gem -v
  - bundle -v

configuration:

- Master 

platform:

- x64

image:

- Visual Studio 2017

environment:

  matrix:

  - BUILD_MODE: MSBuild

deploy_script: 
  - puppet-configure.ps1

# Disable build through solution file
build: off

