version: 1.0.{build}
clone_depth: 3
skip_tags: true

configuration:

- Debug
- Release

platform:

- Win32
- x64

image:

- Visual Studio 2017
- Visual Studio 2015
- Visual Studio 2013

environment:

  matrix:

  - BUILD_MODE: MSBuild

# Disable build through solution file
build: off

